apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hello-app
  name: hello-app
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hello-app
  type: NodePort
status:
  loadBalancer: {}
