name: Verificar PR de deploy

on:
  pull_request:
    branches:
      - main

jobs:
    validate-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout do PR
              uses: actions/checkout@v3

            - name: Verificar se o PR pode ser mesclado
              run: |
                if [ "${{ github.event.pull_request.mergeable }}" != "true" ]; then
                  echo "O PR não pode ser mesclado automaticamente."
                  exit 1
                fi
                echo "O PR está apto para merge."

            - name: Mostrar imagem atualizada
              run: |
                grep image: manifests/deployment.yaml